version: '3'
services:
  ingress:
    image: nginx:1.19
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../front:/app
      - ../logs/nginx/access.log:/var/log/nginx/access.log
      - ../logs/nginx/error.log:/var/log/nginx/error.log
      - /home/ubuntu/HottestTechs/acme.sh/toptechs.xyz/fullchain.cer:/etc/certs/fullchain.pem
      - /home/ubuntu/HottestTechs/acme.sh/toptechs.xyz/toptechs.xyz.key:/etc/certs/privkey.pem
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped

  goapi:
    build:
      context: ../back
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
    volumes:
      - ../logs/api/:/var/log/api/
    expose:
      - '8090'
    restart: unless-stopped

    netdata:
    image: netdata/netdata
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
    volumes:
      - ./netdata/netdata.conf:/etc/netdata/netdata.conf
      - ./netdata/web_log.conf:/etc/netdata/go.d/web_log.conf
      - ./netdata/nginx.conf:/etc/netdata/go.d/nginx.conf
      - ../storage/netdatalib:/var/lib/netdata
      - ../storage/netdatacache:/var/cache/netdata
      - ../logs/nginx/access.log:/var/log/nginx/access.log
      - ../logs/nginx/error.log:/var/log/nginx/error.log
      - ../logs/netdata/access.log:/var/log/netdata/access.log
      - ../logs/netdata/error.log:/var/log/netdata/error.log
      - ../logs/netdata/debug.log:/var/log/netdata/debug.log
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    user: ${CURRENT_UID}
